node {
    def dockerImage = docker.image('cimg/node:16.20')
    dockerImage.pull()
    dockerImage.inside('-p 3000:3000 -u root') {
        stage('Build') {
            sh 'npm install'
        }

        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }

        stage('Manual Approval') {
            input message: 'Apakah anda melanjutkan ke tahap Deploy? (Klik "Proceed" untuk mengakhiri)'
        
        }

        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            sh 'pwd && cd build && ls -la'
            sshagent(credentials: ['sshec2']) {
                sh """
                    scp -r -o StrictHostKeyChecking=no build ${env.EC2_USER}@${env.EC2_HOST}:/home/ubuntu/react-app
                """
            }
            sleep 60
        }
    }
}